# Snapshot report for `test/register.js`

The actual snapshot is saved in `register.js.snap`.

Generated by [AVA](https://ava.li).

## should work using both the -r flag and init() | [multipleResolves]

> Snapshot 1

    {
      code: 0,
      stderr: '',
      stdout: '',
    }

## should work using both the -r flag and init() | [rejectionHandled]

> Snapshot 1

    {
      code: 0,
      stderr: '',
      stdout: '',
    }

## should work using both the -r flag and init() | [uncaughtException]

> Snapshot 1

    {
      code: 0,
      stderr: '',
      stdout: '',
    }

## should work using both the -r flag and init() | [unhandledRejection]

> Snapshot 1

    {
      code: 0,
      stderr: '',
      stdout: '',
    }

## should work using both the -r flag and init() | [warning]

> Snapshot 1

    {
      code: 0,
      stderr: '',
      stdout: '',
    }

## should work using the -r flag | [multipleResolves]

> Snapshot 1

    {
      code: 0,
      stderr: '',
      stdout: `i  multipleResolves (a promise was  multiple times) ␊
      Initially resolved with: { success: true }␊
      Then rejected with: Error: message␊
          at STACK TRACE`,
    }

## should work using the -r flag | [rejectionHandled]

> Snapshot 1

    {
      code: 0,
      stderr: `×  unhandledRejection (a promise was rejected but not handled)  Error: message␊
          at STACK TRACE␊
       ×  rejectionHandled (a promise was rejected and handled too late)  Error: message␊
          at STACK TRACE`,
      stdout: '',
    }

## should work using the -r flag | [uncaughtException]

> Snapshot 1

    {
      code: 1,
      stderr: `×  uncaughtException (an exception was thrown but not caught)  Error: message␊
          at STACK TRACE`,
      stdout: '',
    }

## should work using the -r flag | [unhandledRejection]

> Snapshot 1

    {
      code: 0,
      stderr: `×  unhandledRejection (a promise was rejected but not handled)  Error: message␊
          at STACK TRACE`,
      stdout: '',
    }

## should work using the -r flag | [warning]

> Snapshot 1

    {
      code: 0,
      stderr: `‼  warning (WarningType)  message␊
      [500] Detail␊
          at STACK TRACE`,
      stdout: '',
    }

## should work with --no-warnings | [multipleResolves]

> Snapshot 1

    {
      code: 0,
      stderr: '',
      stdout: `i  multipleResolves (a promise was  multiple times) ␊
      Initially resolved with: { success: true }␊
      Then rejected with: Error: message␊
          at STACK TRACE`,
    }

## should work with --no-warnings | [rejectionHandled]

> Snapshot 1

    {
      code: 0,
      stderr: `×  unhandledRejection (a promise was rejected but not handled)  Error: message␊
          at STACK TRACE␊
       ×  rejectionHandled (a promise was rejected and handled too late)  Error: message␊
          at STACK TRACE`,
      stdout: '',
    }

## should work with --no-warnings | [uncaughtException]

> Snapshot 1

    {
      code: 1,
      stderr: `×  uncaughtException (an exception was thrown but not caught)  Error: message␊
          at STACK TRACE`,
      stdout: '',
    }

## should work with --no-warnings | [unhandledRejection]

> Snapshot 1

    {
      code: 0,
      stderr: `×  unhandledRejection (a promise was rejected but not handled)  Error: message␊
          at STACK TRACE`,
      stdout: '',
    }

## should work with --no-warnings | [warning]

> Snapshot 1

    {
      code: 0,
      stderr: `‼  warning (WarningType)  message␊
      [500] Detail␊
          at STACK TRACE`,
      stdout: '',
    }
